library(readr)
library(dplyr)
library(tidyr)
library(tidyverse)

df <- read_csv("FILTERED DATA.csv") %>%
  mutate(OUTCOME = case_when(
    (RESULT == "HIT" | RESULT == "GOAL" | RESULT == "BEHIND" | RESULT == "NO SCORE") ~ 'EFFECTIVE',
    (RESULT == "NEUTRAL" | (RESULT == "NO DISPOSAL" & lead(TEAM_BALL == "STOPPAGE", 1)) | (RESULT == "NO DISPOSAL" & lead(TEAM_BALL == "OFFENCE WIN", 1))) ~ 'NEUTRAL',
    (RESULT == "MISS" | (RESULT == "NO DISPOSAL" & lead(TEAM_BALL == "DEFENCE WIN", 1))) ~ 'INEFFECTIVE'
  )) %>%
  drop_na(PHASE_DURATION) %>% 
 # mutate(Frequency.bin = cut(PHASE_START, breaks = seq(from = 0, to = 9000, by = 120))) %>%
  mutate(Freq_dur = 60/PHASE_DURATION) %>% 
 # drop_na(Freq_dur) %>% 
  select(#Frequency.bin, 
    PHASE, PHASE_DURATION, Freq_dur, everything())




# create new dataframe with relevant columns standardised per hour.

#df.filtered <- df %>%
#  select(RAIN, WIND, DATE, PLAYER, WEEK, DAY, DATE, SETTING, NUMBER, START_TIME, DURATION, CARRIER_DENSITY, DIRECTION, DISPOSAL, DISTANCE, GAIN_POSS, KEY_MOMENT, LOCATION, MOVEMENT, PRESSURE, RECEIVER_DENSITY, RESULT, TEAM_BALL, LOCATION_START, LOCATION_END, X_VALUE_START, Y_VALUE_START, X_VALUE_END, Y_VALUE_END, DIST_TO_GOAL_START, DIST_TO_GOAL_END, DIST_TO_OPPO_GOAL_START, DIST_TO_OPPO_GOAL_END, ZONE_START, ZONE_END, IN50_ENTRY, REBOUND_50, PRESSURE_POINTS, CHAIN_METRES_GAINED, CHAIN_METRES_PER_SEC, OUTCOME, Frequency.bin)

# select relevant columns and apply loop to standardise for time

df.filtered <- df %>%
 # dplyr::group_by(SETTING, WEEK, Frequency.bin, RAIN, WIND, DATE) %>%
  filter(PHASE_DURATION > 0) %>% 
  dplyr::group_by(DATE, SETTING, WEEK, PHASE) %>%
  summarise(
    # TEAM WON BALL
    OFF_WIN_PERMIN = (sum(TEAM_BALL == "OFFENCE WIN", na.rm = T)*Freq_dur), 
    DEF_WIN_PERMIN = (sum(TEAM_BALL == "DEFENCE WIN", na.rm = T)*Freq_dur), 
    STOPPAGE_PERMIN = (sum(TEAM_BALL == "STOPPAGE", na.rm = T)*Freq_dur),
    #POSS TYPE
    MARK_PERMIN = (sum(GAIN_POSS == "MARK", na.rm = T)*Freq_dur), 
    GP_PERMIN = (sum(GAIN_POSS == "GP", na.rm = T)*Freq_dur), 
    GB_PERMIN = (sum(GAIN_POSS == "GROUNDBALL-GET", na.rm = T)*Freq_dur), 
    #DISPOAL TYPE
    KICKS_PERMIN = (sum(DISPOSAL == "KICK", na.rm = T)*Freq_dur), 
    HB_PERMIN = (sum(DISPOSAL == "HANDBALL", na.rm = T)*Freq_dur), 
    TACKLED = (sum(DISPOSAL == "TACKLED", na.rm = T)*Freq_dur),
    NO_DISP_PERMIN = (sum(DISPOSAL == "NO DISPOSAL", na.rm = T)*Freq_dur),
    #TIP
    DURATION_0_1S_PERMIN = (sum(DURATION <=1, na.rm = T)*Freq_dur), 
    DURATION_1_2S_PERMIN = (sum(DURATION >1 & DURATION <=2, na.rm = T)*Freq_dur), 
    DURATION_2_3S_PERMIN = (sum(DURATION >2 & DURATION <=3, na.rm = T)*Freq_dur), 
    DURATION_MORE3S_PERMIN = (sum(DURATION >3, na.rm = T)*Freq_dur), 
    #MOVEMENT
    DYNAMIC_PERMIN = (sum(MOVEMENT == "DYNAMIC", na.rm = T)*Freq_dur), 
    STATIONARY_PERMIN = (sum(MOVEMENT == "STATIONARY", na.rm = T)*Freq_dur), 
    #PRESSURE
    PHYSICAL_PER_MIN = (sum(PRESSURE == "PHYSICAL", na.rm = T)*Freq_dur), 
    CLOSING_PER_MIN = (sum(PRESSURE == "CLOSING", na.rm = T)*Freq_dur), 
    CHASING_PER_MIN = (sum(PRESSURE == "CHASING", na.rm = T)*Freq_dur), 
    CORRALLING_PER_MIN = ((sum(PRESSURE == "CORRALLING", na.rm = T))*Freq_dur), 
    NO_PRESSURE_PER_MIN = (sum(PRESSURE == "NO PRESSURE", na.rm = T)*Freq_dur), 
    #CARRIER DENSITY
    MORE3_OPPO_PERMIN = (sum(CARRIER_DENSITY == "MORE 3 OPPO", na.rm = T)*Freq_dur), 
    THREE_OPPO_PERMIN = (sum(CARRIER_DENSITY == "3 OPPO", na.rm = T)*Freq_dur), 
    TWO_OPPO_PER_MIN = (sum(CARRIER_DENSITY == "2 OPPO", na.rm = T)*Freq_dur), 
    ONE_OPPO_PER_MIN = (sum(CARRIER_DENSITY == "1 OPPO", na.rm = T)*Freq_dur), 
    NO_OPPO_PER_MIN = (sum(CARRIER_DENSITY == "NO OPP", na.rm = T)*Freq_dur), 
    #DISTANCE
    SHORT_DIST_PERMIN = (sum(DISTANCE == "0-25M", na.rm = T)*Freq_dur), 
    MEDIUM_DIST_PERMIN = (sum(DISTANCE == "25-40M", na.rm = T)*Freq_dur), 
    LONG_DIST_PERMIN = (sum(DISTANCE == "40", na.rm = T)*Freq_dur), 
    DIST_NO = (sum(DISTANCE == "NO DISPOSAL", na.rm = T)*Freq_dur),
    #RECEIVER DENSITY
    UNCONTESTED_PERMIN = (sum(RECEIVER_DENSITY == "UNCONTESTED", na.rm = T)*Freq_dur),
    EVEN_PERMIN = (sum((RECEIVER_DENSITY == "EVEN") | (RECEIVER_DENSITY == "CONTEST"), na.rm = T)*Freq_dur),
    SUPERIOR_PERMIN = (sum(RECEIVER_DENSITY == "SUPERIOR", na.rm = T)*Freq_dur),
    INFERIOR_PERMIN = (sum(RECEIVER_DENSITY == "INFERIOR", na.rm = T)*Freq_dur),
    LEADING_PERMIN = (sum(RECEIVER_DENSITY == "LEADING", na.rm = T)*Freq_dur),
    SHOT_GOAL_PERMIN = (sum(RECEIVER_DENSITY == "SHOT AT GOAL", na.rm = T)*Freq_dur),
    NO_RECIEVER_PERMIN = (sum(RECEIVER_DENSITY == "NO RECEIVER", na.rm = T)*Freq_dur),
    RECIEVE_NO = (sum(RECEIVER_DENSITY == "NO DISPOSAL", na.rm = T)*Freq_dur),
    #OUTCOME
    EFFECTIVE_PERMIN = (sum(OUTCOME == "EFFECTIVE", na.rm = T)*Freq_dur),
    INEFFECTIVE_PERMIN = (sum(OUTCOME == "INEFFECTIVE", na.rm = T)*Freq_dur),
    NEUTRAL_PERMIN = (sum(OUTCOME == "NEUTRAL", na.rm = T)*Freq_dur)
  ) %>%
  distinct() %>%
  mutate_if(is.numeric, round, digits = 2) %>%
  ungroup() 

write_csv(df.filtered, "PERCENT DATA.csv")

df.descriptive <- df.filtered %>%
  group_by(SETTING, WEEK) %>%
  summarise(
    #team won ball
    OFF_WIN_PERCENT = (sum(OFF_WIN_PERMIN) / sum(OFF_WIN_PERMIN, DEF_WIN_PERMIN, STOPPAGE_PERMIN))*100,
    DEF_PERCENT = (sum(DEF_WIN_PERMIN) / sum(OFF_WIN_PERMIN, DEF_WIN_PERMIN, STOPPAGE_PERMIN))*100,
    STOPPAGE_PERCENT = (sum(STOPPAGE_PERMIN) / sum(OFF_WIN_PERMIN, DEF_WIN_PERMIN, STOPPAGE_PERMIN))*100,
    #gain poss
    MARK_PERCENT = (sum(MARK_PERMIN) / sum(MARK_PERMIN, GP_PERMIN, GB_PERMIN))*100,
    GP_PERCENT = (sum(GP_PERMIN) / sum(MARK_PERMIN, GP_PERMIN, GB_PERMIN))*100,
    GB_PERCENT = (sum(GB_PERMIN) / sum(MARK_PERMIN, GP_PERMIN, GB_PERMIN))*100,
    #disposal type
    KICK_PERCENT = (sum(KICKS_PERMIN) / sum(KICKS_PERMIN, HB_PERMIN, TACKLED))*100,
    HB_PERCENT = (sum(HB_PERMIN) / sum(KICKS_PERMIN, HB_PERMIN, TACKLED))*100,
    TACKLED_PERCENT = sum((TACKLED) / sum(KICKS_PERMIN, HB_PERMIN, TACKLED))*100,
    #TIP
    DUR_01_PERCENT = (sum(DURATION_0_1S_PERMIN) / sum(DURATION_0_1S_PERMIN, DURATION_1_2S_PERMIN, DURATION_2_3S_PERMIN, DURATION_MORE3S_PERMIN))*100,
    DUR_12_PERCENT = (sum(DURATION_1_2S_PERMIN) / sum(DURATION_0_1S_PERMIN, DURATION_1_2S_PERMIN, DURATION_2_3S_PERMIN, DURATION_MORE3S_PERMIN))*100,
    DUR_23_PERCENT = (sum(DURATION_2_3S_PERMIN) / sum(DURATION_0_1S_PERMIN, DURATION_1_2S_PERMIN, DURATION_2_3S_PERMIN, DURATION_MORE3S_PERMIN))*100,
    DUR_3MORE_PERCENT = (sum(DURATION_MORE3S_PERMIN) / sum(DURATION_0_1S_PERMIN, DURATION_1_2S_PERMIN, DURATION_2_3S_PERMIN, DURATION_MORE3S_PERMIN))*100,
    # movement
    DYNAMIC_PERCENT = (sum(DYNAMIC_PERMIN) / sum(DYNAMIC_PERMIN, STATIONARY_PERMIN))*100,
    STATIONARY_PERCENT = (sum(STATIONARY_PERMIN) / sum(DYNAMIC_PERMIN, STATIONARY_PERMIN))*100,
    # pressure
    PHYSICAL_PERCENT = (sum(PHYSICAL_PER_MIN) / sum(PHYSICAL_PER_MIN, CLOSING_PER_MIN, CHASING_PER_MIN, CORRALLING_PER_MIN, NO_PRESSURE_PER_MIN))*100,
    CLOSING_PERCENT = (sum(CLOSING_PER_MIN) / sum(PHYSICAL_PER_MIN, CLOSING_PER_MIN, CHASING_PER_MIN, CORRALLING_PER_MIN, NO_PRESSURE_PER_MIN))*100,
    CHASING_PERCENT = (sum(CHASING_PER_MIN) / sum(PHYSICAL_PER_MIN, CLOSING_PER_MIN, CHASING_PER_MIN, CORRALLING_PER_MIN, NO_PRESSURE_PER_MIN))*100,
    CORRALLING_PERCENT = (sum(CORRALLING_PER_MIN) / sum(PHYSICAL_PER_MIN, CLOSING_PER_MIN, CHASING_PER_MIN, CORRALLING_PER_MIN, NO_PRESSURE_PER_MIN))*100,
    NOPRESS_PERCENT = (sum(NO_PRESSURE_PER_MIN) / sum(PHYSICAL_PER_MIN, CLOSING_PER_MIN, CHASING_PER_MIN, CORRALLING_PER_MIN, NO_PRESSURE_PER_MIN))*100,
    #density
    MORE3OPPO_PERCENT = (sum(MORE3_OPPO_PERMIN) / sum(MORE3_OPPO_PERMIN, THREE_OPPO_PERMIN, TWO_OPPO_PER_MIN, ONE_OPPO_PER_MIN, NO_OPPO_PER_MIN))*100,
    THREEOPPO_PERCENT = (sum(THREE_OPPO_PERMIN) / sum(MORE3_OPPO_PERMIN, THREE_OPPO_PERMIN, TWO_OPPO_PER_MIN, ONE_OPPO_PER_MIN, NO_OPPO_PER_MIN))*100,
    TWOOPPO_PERCENT = (sum(TWO_OPPO_PER_MIN) / sum(MORE3_OPPO_PERMIN, THREE_OPPO_PERMIN, TWO_OPPO_PER_MIN, ONE_OPPO_PER_MIN, NO_OPPO_PER_MIN))*100,
    ONEOPPO_PERCENT = (sum(ONE_OPPO_PER_MIN) / sum(MORE3_OPPO_PERMIN, THREE_OPPO_PERMIN, TWO_OPPO_PER_MIN, ONE_OPPO_PER_60MIN, NO_OPPO_PER_MIN))*100,
    NOOPPO_PERCENT = (sum(NO_OPPO_PER_MIN) / sum(MORE3_OPPO_PERMIN, THREE_OPPO_PERMIN, TWO_OPPO_PER_MIN, ONE_OPPO_PER_MIN, NO_OPPO_PER_MIN))*100,
    # distance
    SHORT_PERCENT = (sum(SHORT_DIST_PERMIN) / sum(SHORT_DIST_PERMIN, MEDIUM_DIST_PERMIN, LONG_DIST_PERMIN, DIST_NO))*100,
    MEDIUM_PERCENT = (sum(MEDIUM_DIST_PERMIN) / sum(SHORT_DIST_PERMIN, MEDIUM_DIST_PERMIN, LONG_DIST_PERMIN, DIST_NO))*100,
    LONG_PERCENT = (sum(LONG_DIST_PERMIN) / sum(SHORT_DIST_PERMIN, MEDIUM_DIST_PERMIN, LONG_DIST_PERMIN, DIST_NO))*100,
    DIST_NO_PERCENT = (sum(DIST_NO) / sum(SHORT_DIST_PERMIN, MEDIUM_DIST_PERMIN, LONG_DIST_PERMIN, DIST_NO))*100,
    # receiver density
    EVEN_PERCENT = (sum(EVEN_PERMIN) / sum(EVEN_PERMIN, SUPERIOR_PERMIN, INFERIOR_PERMIN, LEADING_PERMIN, UNCONTESTED_PERMIN, NO_RECIEVER_PERMIN, RECIEVE_NO, SHOT_GOAL_PERMIN))*100,
    SUPERIOR_PERCENT = (sum(SUPERIOR_PERMIN) / sum(EVEN_PERMIN, SUPERIOR_PERMIN, INFERIOR_PERMIN, LEADING_PERMIN, UNCONTESTED_PERMIN, NO_RECIEVER_PERMIN, RECIEVE_NO, SHOT_GOAL_PERMIN))*100,
    INFERIOR_PERCENT = (sum(INFERIOR_PERMIN) / sum(EVEN_PERMIN, SUPERIOR_PERMIN, INFERIOR_PERMIN, LEADING_PERMIN, UNCONTESTED_PERMIN, NO_RECIEVER_PERMIN, RECIEVE_NO, SHOT_GOAL_PERMIN))*100,
    LEADING_PERCENT = (sum(LEADING_PERMIN) / sum(EVEN_PERMIN, SUPERIOR_PERMIN, INFERIOR_PERMIN, LEADING_PERMIN, UNCONTESTED_PERMIN, NO_RECIEVER_PERMIN, RECIEVE_NO, SHOT_GOAL_PERMIN))*100,
    UNCONTESTED_PERCENT = (sum(UNCONTESTED_PERMIN) / sum(EVEN_PERMIN, SUPERIOR_PERMIN, INFERIOR_PERMIN, LEADING_PERMIN, UNCONTESTED_PERMIN, NO_RECIEVER_PERMIN, RECIEVE_NO, SHOT_GOAL_PERMIN))*100,
    NO_RECEIVER_PERCENT = (sum(NO_RECIEVER_PERMIN) / sum(EVEN_PERMIN, SUPERIOR_PERMIN, INFERIOR_PERMIN, LEADING_PERMIN, UNCONTESTED_PERMIN, NO_RECIEVER_PERMIN, RECIEVE_NO, SHOT_GOAL_PERMIN))*100,
    NO_RECEIVER_TACKLED_PERCENT = (sum(RECIEVE_NO) / sum(EVEN_PERMIN, SUPERIOR_PERMIN, INFERIOR_PERMIN, LEADING_PERMIN, UNCONTESTED_PERMIN, NO_RECIEVER_PERMIN, RECIEVE_NO, SHOT_GOAL_PERMIN))*100,
    SHOT_GOAL_PERCENT = (sum(SHOT_GOAL_PERMIN) / sum(EVEN_PERMIN, SUPERIOR_PERMIN, INFERIOR_PERMIN, LEADING_PERMIN, UNCONTESTED_PERMIN, NO_RECIEVER_PERMIN, RECIEVE_NO, SHOT_GOAL_PERMIN))*100,
    #Outcome
    EFFECTIVE_PERCENT = (sum(EFFECTIVE_PERMIN) / sum(EFFECTIVE_PERMIN, INEFFECTIVE_PERMIN, NEUTRAL_PERMIN))*100,
    INEFFECTIVE_PERCENT = (sum(INEFFECTIVE_PERMIN) / sum(EFFECTIVE_PERMIN, INEFFECTIVE_PERMIN, NEUTRAL_PERMIN))*100,
    NEUTRAL_PERCENT = (sum(NEUTRAL_PERMIN) / sum(EFFECTIVE_PERMIN, INEFFECTIVE_PERMIN, NEUTRAL_PERMIN))*100
  ) %>%
  mutate_if(is.numeric, round, digits = 2)





write_csv(df.descriptive, "PERCENT DATA2.csv")

